#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bash ~/.config/polybar/launch.sh --forest &

feh --bg-fill -z .walls/ &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
picom &

conky -c .conky/Style_Retro.conkyrc &

~/.config/spectrumyzer/spectrumyzer.py &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
